# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'chasquiApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for chasquiApp
  pod 'SnapKit'
  pod 'IQKeyboardManagerSwift'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SwiftyUserDefaults'
  pod 'SwiftyTimer'

  #RemoteConfig
  pod 'Firebase/Core'
  pod 'Firebase/RemoteConfig'
  
  #Performance
  pod 'Firebase/Performance'

  #IGListKit
  pod 'IGListKit'

  #Rating
  pod 'Cosmos'
  
  #Images
  pod 'SDWebImage'


end
